source "https://rubygems.org"

# use local theme gem for testing
gem "minimal-mistakes-jekyll", path: "../"
group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.0'
end


gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "webrick"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo'
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]